name: 'Upload to GCS'
description: 'Upload files to a GCS bucket'
inputs:
  source-directory:
    description: 'directory to upload from'
    required: true
  sources:
    description: 'globbing patterns to select the files to upload, one per line'
    required: true
  cache-control:
    description: 'cache-control header to set'
    required: true
  destination:
    description: 'bucket and optional prefix'
    required: true
  credentials:
    description: 'service account JSON key'
    required: true
  gzip-extensions:
    description: 'extensions to gzip before uploading'
    required: false
    default: 'css,js,html,eot,ico,otf,ttf,json,svg'
  max-parallel:
    description: 'maximum number to upload in parallel'
    required: false
    default: '20'
runs:
  using: 'node12'
  main: 'dist/index.js'
